@startuml EI01_GET_Activity
title Base Level Interview GET- Activity Diagram (Neurogolondrina)


|User|
start
:Click on 'Entrevista inicial' for a specific user;

|System|
:Validates session;

if (Valid session?) then (yes)
    #D6EAF8:Get identification card data;
    #D6EAF8:Render view;
    |User|
    :Click on 'Siguiente';
    |System|
    #D6EAF8:Get family situation data;
    #D6EAF8:Render view;
    |User|
    :Click on 'Siguiente';
    |System|
    #D6EAF8:Get work situation data;
    #D6EAF8:Render view;

else (no)
    |System|
    :Show message 'please login again';
    stop

endif
stop

@enduml