@startuml Consultar Publicaciones
title Consultar Publicaciones

actor "Usuario" as user

box "Front"
  boundary "Views" as views
end box

box "Presentation"
  boundary "Routes" as routes
  control "Controller" as controller
end box

box "Application"
  control "UseCase" as usecase
  entity "ForumPostDTO" as dto
end box

box "Domain"
  entity "IPublicacionRepository" as repo_iface
end box

box "Infrastructure"
  entity "PublicacionRepository" as repo_impl
  database "Database" as db
end box

user -> views : 1. clic "Ver publicaciones"
activate views

views -> routes : 2. GET /Foro
activate routes

routes -> controller : 3. get_foro(request,response)
activate controller

controller -> usecase : 4. execute({ page, limit })
activate usecase

usecase -> repo_iface : 5. fetchAll({ page, limit })
activate repo_iface

repo_iface -> repo_impl : 6. fetchAll({ page, limit })
activate repo_impl

repo_impl -> db : 7. execute("SELECT * FROM Publicaciones")
activate db

db --> repo_impl : 8. rows
deactivate db

repo_impl --> repo_iface : 9. rows
deactivate repo_impl

repo_iface --> usecase : 10. PublicacionObjetos[]
deactivate repo_iface

usecase -> dto : 11. ForumPostDTO.fromArray(PublicacionObjetos[])
activate dto

dto --> usecase : 12. ForumPostDTO[]
deactivate dto

usecase --> controller : 13. ForumPostDTO[]
deactivate usecase

controller --> routes : 14. res 200 JSON
deactivate controller

routes --> views : 15. HTTP Response
deactivate routes

views --> user : 16. UI actualizada
deactivate views

@enduml
