@startuml Consul_Forum
title Consult Forum

|Usuario|
start
:Click on  "Forum";

|Sistem|
if (¿There's posts?) then (no)
    :Shows message 'No hay publicaciones disponibles';
else (yes)
    :load list of publications;
    :Show publications to the user;
endif

|Usuario|
:See forum;

stop
@enduml