@startuml EI02_Activity

title Socioeconomic Level Interview - Activity Diagram (NeuPsi-Pro)

|User|
start

:Click\n**[+] (Create user)**;

|System|
if (Valid session) then (yes)
    :"Create User" view;
    repeat
    |System|
    :Show previously filled fields;
    |User|
    :Insert user info;
    :Select **[Guardar]**;
    |System|
    backward:Message **Llene los**\n**campos requeridos** ;
    repeat while (Filled required fields) is (no) not (yes)
    :Save user;
    :Message **Usuario**\n**guardado correctamente**;
    :"Users" view;

else (no)
    |System|
    :"Sign in" view;

endif
stop

@enduml