@startuml Create User

actor "Clinic User" as USR

participant "UsersView" as UV
participant "PostUserView" as PUV
participant "main.js" as MAIN
participant "UserRoutes" as ROUTE
participant "UserController" as CTRL
participant "regUserUseCase" as UC
participant "User\n(Entity)" as ENT
participant "RegUserRepo" as REPO
participant "ImpUserRepo" as IREPO
database DB

USR -> UV : Go to user
UV --> USR : Show User View

USR -> UV : Click [+]
UV -> MAIN : navigate('/users/create-user')
MAIN -> PUV : render()
PUV --> USR : Show forms\n(nombre(s)*, apellido paterno*, apellido\nmaterno*, fecha de nacimiento*,\nusuario*, contraseña*, folio*, modalidad*,\nfecha de nacimiento*, fecha de\namputación*, ingreso a neuropsicología*,\namputation ethiology*,amputation level*,\npares*, lateralidad* protesista*, fase*,\nasignado*, foto?)

USR -> PUV : Complete Form
USR -> PUV : Click [Guardar]

PUV -> PUV : validate required fields
alt Empty field
    PUV --> USR : Error "Rellene todos los capos requeridos"
end

PUV -> MAIN : submitUser(first_name,\npaternal_lastname,\nmaternal_lastname,\nbirthdate, user_name,\npassword, modality\nreference_number,\namputation_date,\nneuro_entry_date,\nbase_pathology,\namputation_level,\nneuro_status, pairs, laterality,\nprothesist, assigned,\nprofile_photo?)
MAIN -> ROUTE : POST /api/users/user\n[Authorization: Bearer JWT]

ROUTE -> ROUTE : authMiddleware\n verify JWT → id_user
ROUTE -> CTRL : controller.createUser(req, res)

CTRL -> CTRL : req.body / req.file {first_name,\npaternal_lastname, maternal_lastname,\nbirthdate, user_name, password,\nreference_number, modality,\namputation_date, neuro_entry_date,\nbase_pathology, amputation_level,\nneuro_status, pairs, laterality,\nprothesist, assigned, profile_photo?}

CTRL -> UC : CreateUserUseCase.execute({ id_user,\nfirst_name, paternal_lastname,\nmaternal_lastname, birthdate,\nuser_name, password_hash,\nreference_number, modality,\namputation_date, neuro_entry_date,\nbase_pathology, amputation_level,\nneuro_status, pairs, laterality,\nprothesist, assigned, profile_photoPath?})

UC -> UC : Validate (empty first_name,\nempty paternal_lastname,\nempty birthdate,\nempty user_name,\nempty password_hash,\nempty reference_number,\nempty modality,\nempty amputation_date,\nempty neuro_entry_date,\nempty base_pathology,\nempty amputation_level,\nempty neuro_status,\nempty pairs,\nempty laterality, empty\nprothesist, empty assigned,\nunvalid id_user)
alt Validación falla
    UC --> CTRL : throw DomainError(message)
    CTRL --> ROUTE : HTTP 422 { error }
    ROUTE --> MAIN : HTTP 422 { error }
    MAIN --> PUV : Shows error to the Clinic user
end

UC -> ENT : new User({\nid_user, first_name,\npaternal_lastname,\nmaternal_lastname, birthdate,\nuser_name, password_hash,\nreference_number, modality,\namputation_date,\nneuro_entry_date,\nbase_pathology,\namputation_level, neuro_status,\npairs, laterality, prothesist,\nrole: 2\nregistration_date: now() })
ENT -> ENT : Validate\n(required fields, max lenght)
ENT --> UC : userEntity

UC -> IREPO : save(userEntity)

IREPO -> IREPO : Process image\n(saves image → gets path/URL)
IREPO -> DB : INSERT INTO user\n(id_user, id_role, user_name,\nfirst_name, lastname_p,\nlastname_m, birthdate,\npassword_hash)\n\nINSERT INTO user_info\nassigned, neuro_status,\nbase_pathology, modality,\nprofile_photo, registration_date,\nreference_number,\namputation_date, laterality,\nprothesist, neuro_entry_date,\namputation_date, pairs
DB --> IREPO : { id_user }

IREPO -> ENT : user.setId(id_user)
REPO --> UC : userSaved

UC -> UC : map Entity → UserDTO
UC --> CTRL : USerDTO


CTRL --> ROUTE : HTTP 201 Created\n{ data: user }
ROUTE --> MAIN : HTTP 201 Created\n{ data: user }
MAIN -> UV : navigate('/users')\n+ add user to consult users
UV --> USR : Updated users with\nnew user

@enduml