@startuml GU05 Get-User

title Get User - User Management (NeuPsi-Pro)

actor "Clinical Group" as CG

boundary "userListView" as VUsers
boundary "userView" as VOne
control "main.js" as MAIN
boundary "getUser\nRoutes" as ROUTE
control "getUser\nController" as CTRL
control "getUser\nUseCase" as UC
control "users\nRepository" as REPO
entity "User" as ENT
entity "UserDTO" as DTO
database DB

CG -> VUsers : Click [Consultar Usuario]
VUsers -> MAIN : navigate\n('/users/{id_user}')

MAIN -> ROUTE : GET /api/users/{id_user}\n[Authorization: Bearer JWT]

ROUTE -> ROUTE : authMiddleware\nvalidate JWT
ROUTE -> CTRL : getUser(req, res)

CTRL -> CTRL : Extract id_user from req.params

CTRL -> UC : execute({id_user})

UC -> REPO : fetchOne({id_user})

REPO -> DB : SELECT l.*, u.first_name,\nu.lastname_p, u.lastname_m,\nu.profile_photo, u.birthdate,\nu.registration_date,\nu.reference_number,\nuc.first_name AS assigned_clinic\nFROM user_info l\nJOIN users u ON l.id_user = u.id_user\nLEFT JOIN user_relation ur ON u.id_user = ur.id_user\nLEFT JOIN users uc ON ur.id_clinic_user = uc.id_user\nWHERE l.id_user = ?

DB --> REPO : rawData

REPO --> UC : rawData

UC -> ENT : new User(data)
ENT --> UC : UserEntity

UC --> CTRL : UserEntity

CTRL -> DTO : map entities to DTO
DTO --> CTRL : UserDTO

CTRL --> ROUTE : HTTP 200 { data: UserDTO }

ROUTE --> MAIN : HTTP 200 { data: user }

MAIN -> VOne : navigate('/users/{id_user}')\n+ data

VOne --> CG : Display one user view

@enduml