
@startuml
actor "Clinicial User" as CU
boundary "View (Frontend)" as V
participant "getClinicalDashboard.Routes.js" as R
participant "authMiddleware" as AM
participant "getMenuClinical.Controller" as C0
participant "getClinicalDashboard.Controller" as C
participant "getUserInfo.Controller" as C2
participant "getMenuClinicalUsersUseCase" as U0
participant "getClinicalDashboardUseCase" as U
participant "getUserInfoUseCase" as U2
participant "userClinicalSummaryDTO" as D0
participant "dashboardClinicalUserDTO" as D
participant "impClinicalRepository" as IRE0
participant "impClinicalDashboardRepository" as IRE
participant "impAppointRepository" as IRE2
participant "ClinicalRepository" as RE0
participant "ClinicalDashboardRepository" as RE
participant "AppointRepository" as RE2
participant "database" as DB


activate CU
CU -> V: Click on "Mi Panel"
deactivate CU
activate V
V -> R: GET /dashboard/api
activate R
R -> AM: authMiddleware(req, res, next)
deactivate R
activate AM
AM -> AM: Verifies and decodes JWT\n(role, valid session)
AM -> R: next()
deactivate AM
activate R
R -> C0: controller.getMenuClinicalUsers(req, res)
deactivate R
activate C0
C0 -> U0: execute()
deactivate C0
activate U0
U0 -> RE0: fetchClinicalUsers()
activate RE0
RE0 -> IRE0: Extends
deactivate RE0
activate IRE0
IRE0 ->> DB: SELECT\nid_user AS id,\nCONCAT_WS( ' ', first_name, lastname_p, lastname_m) AS full_name\nFROM users\nWHERE id_role = 3\nAND eliminated = 0\nORDER BY user_name ASC 
activate DB
DB -->> IRE0: rows
deactivate DB
IRE0 -->> U0: rows
deactivate IRE0
U0 -> D0: constructor
activate D0
D0 -> U0: userClinicalSummaryDTO
deactivate D0
U0 -> C0: userClinicalSummaryDTO
deactivate U0
activate C0
C0 -> R: response(200).json(userClinicalSummaryDTO)
deactivate C0
activate R
R -> V: json
deactivate R
V -> CU: VIEW
activate CU
CU -> V: Selects Clinical User
deactivate CU
V -> R: GET /dashboard/api/:idClinicalUser
activate R
R -> AM: authMiddleware(req, res, next)
deactivate R
activate AM
AM -> AM: Verifies and decodes JWT\n(role, valid session)
AM -> R: next()
deactivate AM
activate R
R -> C: controller.getClinicalUserDashboard(req, res)
deactivate R
activate C
C -> U: execute({idClinicalUser})
deactivate C
activate U
U -> RE: fetchNumberUsers({idClinicalUser})
activate RE
RE -> IRE: Extend
deactivate RE
activate IRE
IRE ->> DB: 
activate DB
DB -->> IRE: data
deactivate DB
IRE -->> U: data
deactivate IRE
U -> RE: fetchAllWithClinical({idClinicalUser})
activate RE
RE -> IRE: Extend
deactivate RE
activate IRE
IRE ->> DB: SELECT *\n FROM user_info ui\n JOIN user_relation ur ON ur.id_user = ui.id_user \nWHERE ur.id_clinical_user = ?
activate DB
DB -->> IRE: data
deactivate DB
IRE -->> U: data
deactivate IRE
U -> RE: fetchHistoricalNumberUsers({idClinicalUser})
deactivate RE
activate IRE
IRE ->> DB: SELECT *\n FROM user_info ui\n JOIN user_relation ur ON ur.id_user = ui.id_user \nWHERE ur.id_clinical_user = ?
activate DB
DB -->> IRE: data
deactivate DB
IRE -->> U: data
deactivate IRE
U -> RE2: fetchAppointmentWithClinical({idClinicalUser})
activate RE2
RE2 -> IRE2: Extend
deactivate RE2
activate IRE2
IRE2 ->> DB: SELECT *\n FROM appointment a\n JOIN user_relation ur ON ur.id_user_relation = a.id_user_relation \nWHERE ur.id_clinical_user = ?
activate DB
DB -->> IRE2: data
deactivate DB
IRE2 -->> U: data
deactivate IRE2
U -> D: constructor
activate D
D -> U: dashboardClinicalUserDTO
deactivate D
U -> C:dashboardClinicalUserDTO 
deactivate U
C -> R: response(200).json(success:true, dashboardClinicalUserDTO)
deactivate C
activate R
R -> V: json
deactivate R
V -> CU: UI
activate CU
CU -> V: Select user
deactivate CU
V -> R: GET /dashboard/api/user/:idUser
activate R
R -> AM: authMiddleware(req, res, next)
deactivate R
activate AM
AM -> AM: Verifies and decodes JWT\n(role, valid session)
AM -> R: next()
deactivate AM
activate R
R -> C2: controller.getClinicalDashboard(req, res)
deactivate R
activate C2
C2 -> U2: execute({idUser})
deactivate C2
activate U2
U2 -> RE: fetchInfoUser
activate RE
RE -> IRE: Extends
deactivate RE
activate IRE
IRE ->> DB: SELECT u.id_user, ui.reference_number, CONCAT(u.first_name, ' ', u.lastname_p, ' ', COALESCE(u.lastname_m, '')) AS full_name, u.birthdate, u.profile_photo, ...
activate DB
DB -->> IRE: Rows
deactivate DB
IRE -->> U2: Rows
deactivate IRE
U2 -> D: clinicalDashboardDTO.userInfoDTO(rows)
activate D
D -> U2: userInfoDTO
deactivate D
U2 -> C: userInfoDTO
deactivate U2
activate C
C -> R: response(200).json(userInfoDTO)
deactivate C
activate R
R -> V: json
deactivate R
V -> CU: VIEW
activate CU
@enduml
 