@startuml GU25_Activity

title Clinical User Dashboard - Activity Diagram (NeuPsi-Pro)

|User|
start

:Click\n*(Mi Panel)*;

|System|
if (Valid session) then (yes)
    :"Mi Panel Dashboard" view;
    :The system gets the list of clinical users;
    |User|
    :The user selects a clinical user;
    |System|
    :The system fetches the clinical user info;
    :The systems gets the list of users of that clinical user;
    |User|
    :The user selects a user;
    |System|
    :The system gers the user info;
else (no)
    |System|
    :"Sign in" view;

endif
stop

@enduml
