@startuml
actor Clinical_group

participant "View" as View
participant "Routes" as Routes
participant "AuthController" as Controller
participant "JWT Service" as JWT
participant "LogInUseCase" as UseCase
participant "Bcrypt" as Bcrypt
participant "LogInRepository" as Repository
participant "Model" as Model

Clinical_group -> View : Enter username and password, click "Iniciar sesión"
View -> Routes : POST /login
Routes -> Controller : login(username, password)
Controller -> UseCase : executeLogin(credentials)
UseCase -> Repository : findByUsername(credential)
Repository -> Model : execute('SELECT * FROM users WHERE user_name = ?', [username])

alt User found

    Model --> Repository : user json
    Repository --> UseCase : user json
    UseCase -> Bcrypt : compare password hash

    alt passwords match

        UseCase --> JWT : generate_token(user, id, role)
        JWT -> UseCase : token

    else passwords dont match

        UseCase --> Controller : error
        Controller --> Routes : HTTP 401
        Routes --> View : Error message
        View --> Grupo_clínico : Invalid credentials

    end

    UseCase --> Controller : token
    
    Controller --> Routes : HTTP 200 GET /homePage
    Routes --> View : HomePage

    View --> Clinical_group : HomePage

else User not found

    Model --> Repository : null
    Repository --> UseCase : null
    UseCase --> Controller : error
    Controller --> Routes : HTTP 401
    Routes --> View : Error message
    View --> Grupo_clínico : Invalid credentials
end

