@startuml IS01
actor Clinical_group

participant "View" as View
participant "Routes" as Routes
participant "PermissionsMiddleware" as Mid
participant "LoginController" as Controller
participant "JWT Service" as JWT
participant "LogInUseCase" as UseCase
participant "AuthUseCase" as authUseCase
participant "UserEntity" as Entity
participant "UserDto" as Dto
participant "PrivilegeDto" as PDto
participant "ExceptionDto" as EDto
participant "Bcrypt" as Bcrypt
participant "LogInRepository" as Repository
participant "SessionRepository" as SRepository
database "DB" as DB

Clinical_group -> View : Enter username and password, click "Iniciar sesión"
View -> Routes : POST /login
Routes -> Controller : login(username, password)
Controller -> UseCase : executeLogin(credentials)
UseCase -> Repository : findByUsername(credential)
Repository -> DB : execute('SELECT * FROM users WHERE user_name = ?', [username])

alt User found

    DB --> Repository : user json
    Repository --> UseCase : user json
    UseCase -> Dto : fromEntity(user)
    Dto --> UseCase : userDto
    UseCase -> Bcrypt : compare password hash

    alt passwords match

        UseCase --> SRepository : createSession(userId, ipAddress, userAgent, expiresAt)
        SRepository --> DB : db.execute('INSERT INTO sessions...')
        DB --> SRepository : query ok
        SRepository --> UseCase : return idSession
        UseCase --> JWT : generate_token(userId, idRole, idSession)
        JWT -> UseCase : token

    else passwords dont match

        UseCase --> Controller : error
        Controller --> Routes : HTTP 401
        Routes --> View : Error message
        View --> Clinical_group : Invalid credentials

    end

    UseCase --> Controller : token
    
    Controller --> Routes : HTTP 200 GET /homePage
    Routes -> Mid : 'consulting', 'homepage'
    Mid --> authUseCase : checkPermission(userId, moduleName, requestedAction)
    authUseCase --> Repository : await PromiseAll[getPrivileges(userId), getExceptions(userId, moduleName)]
    Repository --> DB : db.execute[getPrivileges(userId), getExceptions(userId)]
    DB --> Repository : [privileges, exceptions]
    Repository --> authUseCase : rawUserExceptions, rawRolePrivilege
    authUseCase --> PDto :  fromEntity(rawRolePrivilege)
    authUseCase --> EDto : fromEntity(rawUserExceptions)
    PDto --> authUseCase : privilegeDto
    EDto --> authUseCase : exceptionDto
    authUseCase --> Mid : return exceptions/privileges

    alt has necessary permissions
        Routes --> View: HomePage
        View --> Clinical_group : HomePage
    else has no permissions
        Routes --> View : Error, has no permission for this action
    end

else User not found

    DB --> Repository : null
    Repository --> UseCase : null
    UseCase --> Controller : error
    Controller --> Routes : HTTP 401
    Routes --> View : Error message
    View --> Clinical_group : Invalid credentials
end

