@startuml
skinparam ArchimateBackgroundColor #FFFFFF
skinparam ActivityBackgroundColor #FEFECE
skinparam ActivityBorderColor #A20025
skinparam NoteBackgroundColor #FFF2CC
skinparam NoteBorderColor #B85450

|ClinicUser/Admin|
start
:Authenticated user (Has JWT);
:Presses the "Cerrar sesión" button from the upper bar;

|System|
:Shows confirmation modal on screen;

|ClinicUser/Admin|
if (Do you want to logout?) then ([Cancel])
  |ClinicUser/Admin|
  :Presses "Cancelar";
  |System|
  :Closes the modal;
  :Keeps the user on current screen;
  detach
else ([Confirm])
  |ClinicUser/Admin|
  :Presses "Confirmar";
  |System|
  :Invalidates/Eliminates the JWT local token;
  :Redirects to login screen;
  stop
endif
