class User {
  constructor ({
    idRole,
    userName,
    firstName,
    lastnameP,
    lastnameM,
    email,
    birthdate,
    passwordHash,
    assigned,
    phase,
    basePathology,
    modality,
    profilePhoto,
    referenceNumber,
    laterality,
    prosthetist,
    neuroEntryDate,
    amputationDate,
    amputationLevel,
    pairs,
    sex,
    phone,
  }) {
    this.idRole = idRole,
    this.userName = userName,
    this.firstName = firstName,
    this.lastnameP = lastnameP,
    this.lastnameM = lastnameM || null,
    this.email = email || null,
    this.birthdate = birthdate,
    this.passwordHash = passwordHash,
    this.assigned = assigned,
    this.phase = phase,
    this.basePathology = basePathology,
    this.modality = modality,
    this.profilePhoto = profilePhoto || null,
    this.referenceNumber = referenceNumber,
    this.amputationDate = amputationDate,
    this.amputationLevel = amputationLevel,
    this.laterality = laterality,
    this.prosthetist = prosthetist,
    this.neuroEntryDate = neuroEntryDate || null,
    this.pairs = pairs,
    this.sex = sex,
    this.phone = phone;
  }
}

module.exports = User;
